# Site settings
title: SquawAlpine-TeamPool
email: squawteam@teampools.org
description: > # this means to ignore newlines until "baseurl:"
- this is the SquawAlpine TeamPool project.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: teampools
github_username:  teampools

# Build settings
markdown: kramdown
