# Site settings
title: teampool for squawalpine
email: squawteam@teampools.org
description:  # this means to ignore newlines until "baseurl:"
-  Carpools+ for teams - helping parents have more free time.
-  Team Pools - helping parents have less chaos.
-  Building Community - getting kids to the Squaw teams for the best possible experience.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://teampools.org" # the base hostname & protocol for your site
twitter_username: teampools
github_username:  teampools

# Build settings
markdown: kramdown
